<%@ Page Language="C#" Title="Services" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="Services.aspx.cs" Inherits="WebApplication.Services.Services" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="ServicesGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="ServicesGridView_RowCancelingEdit"
            OnRowDeleting="ServicesGridView_RowDeleting"
            OnRowEditing="ServicesGridView_RowEditing"
            OnRowUpdating="ServicesGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="ServicesGridView_PageIndexChanging"
            Caption="Services" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" ReadOnly="true" />    
                <asp:BoundField DataField="Cost" HeaderText="Cost" SortExpression="Cost" />

                <asp:TemplateField HeaderText="Service type" SortExpression="ServiceType.Name">
                    <EditItemTemplate>
                        <asp:DropDownList ID="ServiceTypesFieldDropDownList" DataSourceID="ServiceTypesSqlDataSource" DataValueField="Id" DataTextField="Name" runat="server"  SelectedValue='<%# Bind("ServiceTypeId") %>'></asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="ServiceTypeId" runat="server" Text='<%# Eval("ServiceType.Name") %>' />
                    </ItemTemplate>
                </asp:TemplateField>

                <asp:TemplateField HeaderText="Employee" SortExpression="Employee.FullName">
                    <EditItemTemplate>
                        <asp:DropDownList ID="EmployeesFieldDropDownList" DataSourceID="EmployeesTypesSqlDataSource" DataValueField="Id" DataTextField="FullName" runat="server"  SelectedValue='<%# Bind("EmployeeId") %>'></asp:DropDownList>
                    </EditItemTemplate>
                    <ItemTemplate>
                        <asp:Label ID="EmployeeId" runat="server" Text='<%# Eval("Employee.FullName") %>' />
                    </ItemTemplate>
                </asp:TemplateField>
            </Columns>
        </asp:GridView>

    </div>
   
    <div style="position:relative;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
       
        <h2>Add service</h2>

        <div>
            <span>Cost: </span>
            <asp:TextBox ID="ServiceCostTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <span>Service type: </span>
            <asp:DropDownList ID="ServiceTypesDropDownList" DataSourceID="ServiceTypesSqlDataSource" DataValueField="Id" DataTextField="Name" runat="server"></asp:DropDownList>
        </div>

        <div>
            <span>Employee: </span>
            <asp:DropDownList ID="EmployeesDropDownList" DataSourceID="EmployeesTypesSqlDataSource" DataValueField="Id" DataTextField="FullName" runat="server"></asp:DropDownList>
        </div>

        <div>
            <asp:Button ID="AddServiceButton" runat="server" Text="Add service" OnClick="AddServiceButton_Click" />
        </div>
    </div>


    
    <asp:SqlDataSource ID="ServiceTypesSqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SqlConnection %>" 
        SelectCommand="SELECT [Id], [Name] FROM [ServiceTypes]">
    </asp:SqlDataSource>

    <asp:SqlDataSource ID="EmployeesTypesSqlDataSource" runat="server" 
        ConnectionString="<%$ ConnectionStrings:SqlConnection %>" 
        SelectCommand="SELECT [Id], [FullName] FROM [Employees]">
    </asp:SqlDataSource>
</asp:Content>

