<%@ Page Title="ServiceTypes" Language="C#" MasterPageFile="~/Site.Master" AutoEventWireup="true" CodeBehind="ServiceTypes.aspx.cs" Inherits="WebApplication.ServiceTypes.ServiceTypes" %>

<asp:Content runat="server" ContentPlaceHolderID="MainContent">
    <div>

        <asp:GridView runat="server" ID="ServiceTypesGridView"
            AutoGenerateColumns="false"
            AllowPaging="true" 
            AutoGenerateDeleteButton="true"
            AutoGenerateEditButton="true" 
            OnRowCancelingEdit="ServiceTypesGridView_RowCancelingEdit"
            OnRowDeleting="ServiceTypesGridView_RowDeleting"
            OnRowEditing="ServiceTypesGridView_RowEditing"
            OnRowUpdating="ServiceTypesGridView_RowUpdating"
            PageSize="10" 
            OnPageIndexChanging="ServiceTypesGridView_PageIndexChanging"
            Caption="Service types" 
            EmptyDataText="Empty" 
            CaptionAlign="Top" 
            PageIndex="0">
            <Columns>
                <asp:BoundField DataField="Id" HeaderText="Id" SortExpression="Id" ReadOnly="true" />    
                <asp:BoundField DataField="Name" HeaderText="Name" SortExpression="Name" />
                <asp:BoundField DataField="Specificaion" HeaderText="Specificaion" SortExpression="Specificaion" />
            </Columns>
        </asp:GridView>

    </div>
    
    <div style="margin-top: 10px;">
        <asp:Label ID="AddStatusLabel" runat="server" Font-Size="XX-Large" Font-Bold="true"></asp:Label>
        <h2>Add Service type</h2>

        <div>
            <span>Name: </span>
            <asp:TextBox ID="ServiceTypeNameTextBox" runat="server"></asp:TextBox>
            <span>Specificaion: </span>
            <asp:TextBox ID="ServiceTypeSpecificaionTextBox" runat="server"></asp:TextBox>
        </div>

        <div>
            <asp:Button ID="AddServiceTypeButton" runat="server" Text="Add service type" OnClick="AddServiceTypeButton_Click" />
        </div>
    </div>
    
</asp:Content>
